# Generated by Django 4.1.3 on 2023-02-09 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cl', models.CharField(max_length=30)),
                ('prenom_cl', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('telephone', models.IntegerField()),
                ('adresse', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('date_achat', models.DateField()),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tarif_heure', models.IntegerField()),
                ('Disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.DateField()),
                ('heure_fin', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.client')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_comment', models.DateField()),
                ('content', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.client')),
            ],
        ),
    ]
