# Generated by Django 4.1.3 on 2023-01-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cl', models.CharField(max_length=30)),
                ('prenom_cl', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('telephone', models.IntegerField()),
                ('adresse', models.CharField(max_length=30)),
            ],
        ),
    ]
