# Generated by Django 4.1.3 on 2023-02-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0003_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='montant',
            field=models.IntegerField(),
        ),
    ]
