# Generated by Django 4.1.3 on 2023-02-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0004_alter_facture_montant'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='vehicule',
    #         name='Disponible',
    #     ),
    # ]
