# Generated by Django 4.1.3 on 2023-02-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0005_remove_vehicule_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='photo',
            field=models.ImageField(default=None, upload_to='vehicules'),
        ),
    ]
