# Generated by Django 4.1.3 on 2023-02-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0006_vehicule_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicule',
            old_name='Disponible',
            new_name='disponible',
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='prix_achat',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
