# Generated by Django 4.1.3 on 2023-02-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0007_rename_disponible_vehicule_disponible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='vehicule',
        ),
    ]
