# Generated by Django 4.1.3 on 2023-02-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0008_remove_voyage_vehicule'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='comment',
        #     old_name='content',
        #     new_name='msg',
        # ),
    ]
