# Generated by Django 4.1.3 on 2023-02-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0009_rename_content_comment_msg'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='vehicule',
            name='photo',
            field=models.ImageField(default=None, upload_to='static/vehicules'),
        ),
    ]
