# Generated by Django 4.1.3 on 2023-02-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0010_rename_content_comment_msg_alter_vehicule_photo'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='comment',
        #     old_name='content',
        #     new_name='msg',
        # ),
        migrations.RenameField(
            model_name='vehicule',
            old_name='designation',
            new_name='modele',
        ),
        migrations.RenameField(
            model_name='vehicule',
            old_name='model',
            new_name='type',
        ),
    ]
