# Generated by Django 4.1.3 on 2023-02-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0011_rename_content_comment_msg_and_more'),
    ]

    operations = [
       
        migrations.RenameField(
            model_name='vehicule',
            old_name='modele',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='vehicule',
            old_name='type',
            new_name='model',
        ),
    ]
