# Generated by Django 4.1.6 on 2023-02-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0012_rename_content_comment_msg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='msg',
        ),
    ]
