# Generated by Django 4.1.3 on 2023-02-13 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0013_rename_content_comment_msg'),
    ]

    operations = [
           
        migrations.AddField(
            model_name='voyage',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='voyage',
            name='vehicule',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='startup.vehicule'),
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
    ]
